### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by yuripace** [ZhangGaoxing/windows-iot-demo#1]
hi
i have a NullReferenceException 
in NRF24L01.cs line 565 (ReceivedData(sender, new ReceivedDataEventArgs(Receive(packetSize))))

**Comment by ZhangGaoxing** [comment]
Hello,
I just tested NRF demo again, no exception was found. If you don't mind, show your code.

Did you call **InitializeAsync()**?
- - - - - - 
Best Wishes
Gaoxing
