### ISSUE TITLE
BH1750FVI LightTransmittance / sensor.read value

### ISSUE THREAD

**Issue by henrikl2000** [ZhangGaoxing/windows-iot-demo#3]
Hi,
Thank you for sharing.
I have 2 question regarding your BH1750FVI demo.
What does LightTransmittance mean and how determine which setting to use?
Is the sensor.Read value returned in Lux? or is it just a value.

/ Henrik

**Comment by ZhangGaoxing** [comment]
Hello henrikl2000,

**What does LightTransmittance mean**

>Some sensors are covered with incomplete transparent obstructions, so we need to set LightTransmittance to correct the value. And also can change the measurement accuracy of luminance. For example, if the transmittance is set to 50%, the measurement accuracy will actually be doubled, and the measurement will be more accurate and effective for the lower luminance environment.

**How determine which setting to use**
>In general, it does not need to be set.

**Is the sensor.Read value returned in Lux? or is it just a value**
>The return value is Lux

- - - - - - 
<h5 align="right">Best wishes</h5>
<h4 align="right">Gaoxing</h4>

**Comment by henrikl2000** [comment]
Thank you for your very fast reply

 

Fra: Zhang Yuexin <notifications@github.com> 
Sendt: Thursday, June 21, 2018 14:00
Til: ZhangGaoxing/windows-iot-demo <windows-iot-demo@noreply.github.com>
Cc: henrikl2000 <henrik@nuhme.dk>; Author <author@noreply.github.com>
Emne: Re: [ZhangGaoxing/windows-iot-demo] BH1750FVI LightTransmittance / sensor.read value (#3)

 

Hello henrikl2000,

What does LightTransmittance mean

Some sensors are covered with incomplete transparent obstructions, so we need to set LightTransmittance to correct the value. And also can change the measurement accuracy of luminance. For example, if the transmittance is set to 50%, the measurement accuracy will actually be doubled, and the measurement will be more accurate and effective for the lower luminance environment.

How determine which setting to use

In general, it does not need to be set.

Is the sensor.Read value returned in Lux? or is it just a value

The return value is Lux

  _____  


Best wishes


Gaoxing
