### ISSUE TITLE
Is IoT.Lightning dead?

### ISSUE THREAD

**Issue by SuperJMN** [ZhangGaoxing/windows-iot-demo#4]
I would like to know if there a better way to deal with PWM than IoT.Lightning.

Thanks in advance!

**Comment by ZhangGaoxing** [comment]
Hi SuperJMN,

I think IoT.Lightning is not dead, this project last commit was 7 month ago.  And IoT.Lightning is just a software PWM, dead or not dead is no difference.

The better way to drive PWM is using hardware PWM, like PCA9685... If there is no special requirement, IoT.Lightning is enough.

<h5 align="right">Best wishes</h5>
<h4 align="right">Gaoxing</h4>
